### ISSUE TITLE
Fix the row segmentation

### ISSUE THREAD

**Issue by amberoldroyd** [Record-Linking-Lab/computer-vision#2]
The model has been trained, but the rows not very accurate, likely because the lines are too faint. Try using a different segmentation tool. Possibly Ransac segmenter from the FHTL

**Comment by haltosan** [comment]
I was told that Daniel Segrera would be able to help out with segmentation. I think we should send him off some image to see how well the current models work.
Do we know if there's any training data that can be sent off too? It might be useful to help his models.

**Comment by ColZoel** [comment]
found workarounds. Used rapid response to manually transcribe
