### ISSUE TITLE
Migrate CV projects in organization Repo to Team Repos

### ISSUE THREAD

**Issue by ColZoel** [Record-Linking-Lab/computer-vision#5]
A bunch of our projects are in the organization repo, it would be great if we could consolidate all of our projects to our team instead. This reduces a bit of clutter for those on the other teams who also use that space. If there is code that would be mutually beneficial to the other teams, we should put that in the organization repos.

**Comment by haltosan** [comment]
Projects and repositories are owned by the organization. There isn't a way I know of to have it only show up in our team. If we view it from our team only, then we don't see other team projects/repositories. There isn't a way to remove it from the organization though.
